export const DUMMY_DATA = [
  {
    likeStatus: true,
    startDate: '2022-10-23',
    participants: 6,
    currentParticipants: 6,
    studyType: '자료구조/알고리즘',
    studyDays: '주말',
    studyTimezone: '오전',
    studyName: '열심히 스터디',
    studyId: Math.floor(Math.random() * 100000),
  },
  {
    likeStatus: false,
    startDate: '2022-08-02',
    participants: 6,
    currentParticipants: 4,
    studyType: '자료구조/알고리즘',
    studyDays: '주말',
    studyTimezone: '오전',
    studyName: '열심히 스터디',
    studyId: Math.floor(Math.random() * 100000),
  },
  {
    likeStatus: false,
    startDate: '2022-08-30',
    participants: 6,
    currentParticipants: 2,
    studyType: '자료구조/알고리즘',
    studyDays: '주말',
    studyTimezone: '오전',
    studyName: '열심히 스터디',
    studyId: Math.floor(Math.random() * 100000),
  },
  {
    likeStatus: false,
    startDate: '2022-08-19',
    participants: 6,
    currentParticipants: 6,
    studyType: '자료구조/알고리즘',
    studyDays: '주말',
    studyTimezone: '오전',
    studyName: '열심히 스터디',
    studyId: Math.floor(Math.random() * 100000),
  },
];
